### PR TITLE
Refactor for Ember 2.x

### PR DESCRIPTION
**Pull request by jandillmann**
Use an instance-initializer to remove the deprecated `application.registry.lookup` call.

### CODE REVIEW

**Comment by jandillmann** [comment]
Does anyone know how to test this? The addon works in my app without the deprecation warning, but the unit test fails to look up `'service:browser-update'`…

**Comment by BryanCrotaz** [comment]
looks good, will merge when tests pass

**Comment by jandillmann** [comment]
:tada:

**Comment by BryanCrotaz** [comment]
Well done :)

**Pull request merged**
